### ISSUE TITLE
a1.2.1 doesn't really work does it?

### ISSUE THREAD

**Issue by kreezxil** [fisty256/AFFS#3]
After doing part 1 of my video showcasing your mod and then rereading your Minecraft forum post and watching your mind-numbing voiceless videos I've come to the shocking conclusion that the only thing that works is the inventory cleaner. Further inventory clean is nothing more than a glorified personal garbage bin and not something that you would install into a machine that would clean the configured items from an entity's inventory as it passes through your field. I further see that the whitelisting feature is working in that I can right click one and it puts my name onto it.
If the force field is working, I'm not sure where it is, the projector shows 0 0 0 for the x y z coords. I teleported there and I didn't see a field. I went to those coords because I didn't see a field where I installed it. The LC said I have 10million force in the projector so I'm at a loss.

My client console log: https://paste.ee/p/JO6Mp

doubt it would be helpful there appear to be no errors in it. hopefully you are not catching errors this early on as those should be thrown so we can report them to you.

If I'm right about your mod not really working, can please update your forum post to indicate that, because as it stands I'm going to have to remove it from pack unless you can tell me what I'm doing wrong, please watch the video I put in your thread. Hopefully you'll say to yourself "That's not what intended, grrrrr gar!!! What is he doing!?" in which case you need to be way more clear.

**Comment by kreezxil** [comment]
Turns out there is something all over the server console, maybe there is a big bug in a1.2.1 something about the owner being null.

https://gist.github.com/0c990d78397662d4dcf0

**Comment by fisty256** [comment]
1. Inventory Cleaner is supposed to ONLY clear YOUR inventory. Not any other. It's just a very simple thing I thought of when I was using the Hammer from Tinker's Construct. I thought it would be cool if I could get rid of the cobble that I was getting. That's the only reason I've added it.

2. The coords in the Force Projector are a offset from the block. So 0, 0, 0 is the projector itself. It's kinda unclear, I know but that's what it is. And just so that you know, you have to apply redstone signal to it in order for it to project the forcefield.

3. The spam in the console is part of unfinished feature that I was working on - Block Protection (only owner can break a block). When I was building this release I turned that feature off becouse it's buggy and kinda doesn't work. I just forgot to delete that debug message. That's it.

4. The error in the server console is a saving error for the new feature I'm talking about above. Not very important.

The only thing this mod is currently useful for is making simple cubed forcefields, killing players using area protector and the inventory cleaner.

I'm sorry but it's a WIP mod (that's why it's in that category on MC forum). All I can say is thanks for reporting these bugs, I'll look into it. :)

**Comment by kreezxil** [comment]
Sure no problem. At least I can finish the mod showcase now. 

Feel free to feature my showcase btw of I hadn't said it already.

-----Original Message-----

**Comment by fisty256** [comment]
Sure, also, have you seen my yesterday's MC Forum post?

**Comment by fisty256** [comment]
Everything should be fixed in upcoming release.

**Comment by kreezxil** [comment]
Depending on when you posted it I may or may not have seen it.
